[build-system]
    requires = ["hatchling"]
    build-backend = "hatchling.build"

[project]
    name = "spectra-assure-sdk"
    dynamic = ['version']

    authors = [
      { name="ReversingLabs" },
    ]

    maintainers = [
      { name="ReversingLabs", email="support@reversinglabs.com" },
    ]

    description = "Python package for interfacing with the Spectra Assure Portal API."
    readme = "README.md"
    requires-python = ">=3.10"
    license = "MIT"

    classifiers = [
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Environment :: Console",
        "Programming Language :: Python :: 3",
        "Topic :: Internet",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ]

    keywords = [
        "Python",
        "Spectra Assure",
        "ReversingLabs",
        "Secure Software",
    ]

    dependencies = [
        "requests==2.33.1",
    ]

[project.urls]
    "Bug Tracker" = "https://github.com/reversinglabs/spectra-assure-sdk/issues"
    "Home Page" = "https://github.com/reversinglabs/spectra-assure-sdk/"
    "Repository" = "https://github.com/reversinglabs/spectra-assure-sdk/"

[tool.hatch.version]
    path = "spectra_assure_api_client/version.py"

[tool.hatch.build]
    only-packages = true

    include = [
        "spectra_assure_api_client/",
    ]

    exclude = [
        "/Old/*",
        "/OLD/*",
        "/lib/*",
        "/etc/*",
        "/bin/*",
        "/testdata/*",
        "Makefile",
        "makefile",
        ".gitignore",
        "/.gitignore",
    ]

[tool.ruff]
    target-version = "py310"
    line-length = 120
    exclude = [
        ".direnv",
        ".eggs",
        ".git",
        ".git-rewrite",
        ".mypy_cache",
        ".nox",
        ".pants.d",
        ".pytype",
        ".ruff_cache",
        ".svn",
        ".tox",
        ".venv",
        "__pypackages__",
        "_build",
        "buck-out",
        "build",
        "dist",
        "node_modules",
        "venv",
        "vtmp",
    ]

[tool.ruff.lint]
    select = [
        "E",      # pycodestyle errors
        "W",      # pycodestyle warnings
        "F",      # Pyflakes
        "UP",     # pyupgrade
        "B",      # flake8-bugbear
        "C4",     # flake8-comprehensions
        "I",      # isort
        "S",      # flake8-bandit
        "T20",    # flake8-print
        "PT",     # flake8-pytest-style
        "Q",      # flake8-quotes
        # "N",      # pep8-naming
        # "D",      # pydocstyle
    ]
    ignore = [
        "T201", # print found
        "PT028", # Test function parameter has default argument
        "S101", # Use of `assert` detected
        "S324", # Probable use of insecure hash functions in `hashlib`: `sha1`
    ]
